/**
 * Utility buckets match the [Tailwind CSS v4](https://tailwindcss.com/docs/) doc sections. Category
 * ids are singular. Order follows the documentation (Layout → … → Accessibility);
 * `flex` and `grid` are separate; `gap-*` is listed on both, with classification using the first
 * match (`flex`). See {@link ./classifyTailwindEdgeCases} (run before
 * {@link ./classify/classifyTailwindUtility} prefix walk).
 *
 * Prefixes match after canonicalization (trim, `!`, lowercase, leading `-`/`_`); the first
 * category whose prefix matches wins; `others` is last and catches the rest.
 */
export const UTILITY_CATEGORIES: readonly {
	readonly id: string;
	readonly prefixes: readonly string[];
}[] = [
	// --- Layout (docs: Layout) ---
	{
		id: "layout",
		prefixes: [
			"container",
			"aspect-",
			"columns-",
			"box-decoration-",
			"box-border",
			"box-content",
			"break-after-",
			"break-before-",
			"break-inside-",
			"inset-",
			"inset-x-",
			"inset-y-",
			"start-",
			"end-",
			"top-",
			"right-",
			"bottom-",
			"left-",
			"z-",
			"anchor-",
			"overflow-",
			"overscroll-",
			"object-",
			"float-",
			"clear-",
			"inline-table",
			"inline-block",
			"flow-root",
			"table-cell",
			"table-row",
			"table-row-group",
			"table-header-group",
			"table-footer-group",
			"table-column",
			"table-column-group",
			"table-caption",
			"static",
			"fixed",
			"absolute",
			"relative",
			"sticky",
			"isolate",
			"block",
			"hidden",
			"flow-root",
			"table",
			"contents",
			"visible",
			"invisible",
			"collapse",
		],
	},
	// --- Flex (docs: Flexbox & grid — flex) ---
	{
		id: "flex",
		prefixes: [
			"flex-",
			"basis-",
			"shrink-",
			"shrink",
			"grow-",
			"grow",
			"justify-",
			"items-",
			"content-",
			"self-",
			"place-",
			"order-",
			"gap-",
			"gap-x-",
			"gap-y-",
		],
	},
	// --- Grid (docs: Flexbox & grid — grid) ---
	{
		id: "grid",
		prefixes: [
			"grid-",
			"grid-cols-",
			"grid-rows-",
			"grid-flow-",
			"col-",
			"row-",
			"auto-cols-",
			"auto-rows-",
			"gap-",
			"gap-x-",
			"gap-y-",
		],
	},
	// --- Spacing (docs: Spacing) ---
	{
		id: "spacing",
		prefixes: [
			"m-",
			"mx-",
			"my-",
			"mt-",
			"mb-",
			"ml-",
			"mr-",
			"ms-",
			"me-",
			"p-",
			"px-",
			"py-",
			"pt-",
			"pb-",
			"pl-",
			"pr-",
			"ps-",
			"pe-",
			"space-x-",
			"space-y-",
		],
	},
	// --- Size (docs: Sizing) ---
	{
		id: "size",
		prefixes: ["min-w-", "max-w-", "min-h-", "max-h-", "size-", "h-", "w-"],
	},
	// --- Text (docs: Typography) ---
	{
		id: "text",
		prefixes: [
			"line-clamp-",
			"line-clamp",
			"text-",
			"font-",
			"leading-",
			"tracking-",
			"indent-",
			"list-",
			"placeholder-",
			"selection-",
			"hyphens-",
			"antialiased",
			"subpixel-antialiased",
			"prose",
			"decoration-",
			"underline",
			"overline",
			"line-through",
			"no-underline",
			"whitespace-",
			"align-",
			"break-",
		],
	},
	// --- Background (docs: Background) ---
	{
		id: "background",
		prefixes: ["bg-", "from-", "via-", "to-"],
	},
	// --- Border (docs: Border) — includes radius (rounded), ring, outline, divide ---
	{
		id: "border",
		prefixes: [
			"ring-offset-",
			"ring-",
			"ring",
			"outline-offset-",
			"outline-",
			"outline",
			"rounded-",
			"rounded",
			"divide-",
			"border-",
			"border",
		],
	},
	// --- Effect (docs: Effect) ---
	{
		id: "effect",
		prefixes: [
			"text-shadow-",
			"drop-shadow-",
			"shadow-",
			"shadow",
			"opacity-",
			"opacity",
			"mask-",
		],
	},
	// --- Filter (docs: Filter) ---
	{
		id: "filter",
		prefixes: [
			"backdrop-",
			"blur-",
			"brightness-",
			"contrast-",
			"grayscale-",
			"hue-rotate-",
			"invert-",
			"saturate-",
			"sepia-",
			"filter-",
			"filter",
		],
	},
	// --- Table (docs: Table) ---
	{
		id: "table",
		prefixes: [
			"border-spacing-",
			"border-spacing-x-",
			"border-spacing-y-",
			"caption-",
		],
	},
	// --- Motion (docs: Transitions and animation) ---
	{
		id: "motion",
		prefixes: [
			"transition-",
			"transition",
			"duration-",
			"ease-",
			"delay-",
			"animate-",
		],
	},
	// --- Transform (docs: Transforms) ---
	{
		id: "transform",
		prefixes: [
			"backface-",
			"translate-",
			"scale-",
			"rotate-",
			"skew-",
			"origin-",
			"transform-",
			"transform",
			"perspective-",
			"perspective",
		],
	},
	// --- Interactivity (docs: Interactivity) ---
	{
		id: "interactivity",
		prefixes: [
			"field-sizing-",
			"color-scheme-",
			"pointer-events-",
			"cursor-",
			"caret-",
			"select-",
			"touch-",
			"scroll-m-",
			"scroll-mx-",
			"scroll-my-",
			"scroll-mt-",
			"scroll-mb-",
			"scroll-ml-",
			"scroll-mr-",
			"scroll-ms-",
			"scroll-me-",
			"scroll-p-",
			"scroll-px-",
			"scroll-py-",
			"scroll-pt-",
			"scroll-pb-",
			"scroll-pl-",
			"scroll-pr-",
			"scroll-ps-",
			"scroll-pe-",
			"scroll-smooth",
			"scroll-auto",
			"accent-",
			"appearance-",
			"appearance",
			/** Custom Highlight API (`::highlight`) */
			"highlight-",
			"resize",
			"snap-",
			"focus-",
			"will-change",
		],
	},
	// --- SVG (docs: SVG) ---
	{
		id: "svg",
		prefixes: ["fill-", "stroke-"],
	},
	// --- Accessibility (docs: Accessibility) ---
	{
		id: "accessibility",
		prefixes: ["sr-only", "not-sr-only", "forced-"],
	},
	{ id: "others", prefixes: [] },
];
