/**
 * Tailwind utility grouping for sidebar filters. Order matters: the first category whose prefix
 *
 * matches wins; `others` must stay last and catches everything else.
 *
 * Prefixes assume the utility was canonicalized for matching (trim, `!`, lowercase, leading `-`/`_`)
 *
 * at the filter boundary — see `canonicalTailwindUtilityForMatch` in `../heuristics/`.
 */
export const UTILITY_CATEGORIES: readonly {
	readonly id: string;
	readonly prefixes: readonly string[];
}[] = [
	{
		id: "text",
		prefixes: [
			"text-",
			"font-",
			"leading-",
			"tracking-",
			"line-clamp-",
			"indent-",
			"list-",
			"placeholder-",
			"caret-",
			"selection-",
			"break-",
			"hyphens-",
			"antialiased",
			"subpixel-antialiased",
			"align-",
			"prose",
			"accent-",
			"decoration-",
			"underline",
			"overline",
			"line-through",
			"no-underline",
		],
	},
	{
		id: "flex",
		prefixes: [
			"inline-flex",
			"flex",
			"shrink-",
			"shrink",
			"grow-",
			"grow",
			"basis-",
			"justify-",
			"items-",
			"content-",
			"self-",
			"place-",
			"order-",
			"gap-",
			"gap-x-",
			"gap-y-",
			"space-x-",
			"space-y-",
		],
	},
	{
		id: "grid",
		prefixes: [
			"grid",
			"col-",
			"row-",
			"auto-cols-",
			"auto-rows-",
			"grid-cols-",
			"grid-rows-",
			"grid-flow-",
			"grid-",
		],
	},
	{
		id: "size",
		prefixes: [
			"min-h-",
			"max-h-",
			"min-w-",
			"max-w-",
			"h-",
			"w-",
			"size-",
			"aspect-",
		],
	},
	{
		id: "position",
		prefixes: [
			"inset-x-",
			"inset-y-",
			"inset-",
			"top-",
			"right-",
			"bottom-",
			"left-",
			"start-",
			"end-",
			"z-",
			"anchor-",
			"isolate",
			"static",
			"fixed",
			"relative",
			"absolute",
			"sticky",
		],
	},
	{
		id: "box",
		prefixes: [
			"container",
			"block",
			"inline-block",
			"inline",
			"flow-root",
			"hidden",
			"table",
			"m-",
			"mx-",
			"my-",
			"mt-",
			"mb-",
			"ml-",
			"mr-",
			"ms-",
			"me-",
			"p-",
			"px-",
			"py-",
			"pt-",
			"pb-",
			"pl-",
			"pr-",
			"ps-",
			"pe-",
			"space-",
			"divide-",
			"overflow-",
			"overscroll-",
			"float-",
			"clear-",
			"object-",
			"opacity-",
			"opacity",
			"visible",
			"invisible",
			"collapse",
			"sr-only",
			"columns-",
			"break-before",
			"break-after",
			"break-inside",
			"box-border",
			"box-content",
		],
	},
	{
		id: "shadow",
		prefixes: ["shadow", "drop-shadow-"],
	},
	{
		id: "rounded",
		prefixes: ["rounded-", "rounded"],
	},
	{
		id: "border",
		prefixes: ["border", "border-", "ring-offset-", "ring-", "ring"],
	},
	{
		id: "background",
		prefixes: ["bg-", "from-", "via-", "to-", "mix-blend-", "bg-blend-"],
	},
	{
		id: "transform",
		prefixes: [
			"translate-",
			"scale-",
			"rotate-",
			"skew-",
			"origin-",
			"transform-none",
			"transform-gpu",
			"transform-cpu",
			"transform",
			"perspective-",
			"perspective",
		],
	},
	{
		id: "motion",
		prefixes: [
			"animate-",
			"transition",
			"transition-",
			"duration-",
			"ease-",
			"delay-",
			"will-change",
		],
	},
	{
		id: "behavior",
		prefixes: [
			"pointer-events-",
			"cursor-",
			"select-",
			"touch-",
			"scroll-smooth",
			"scroll-auto",
			/** Custom Highlight API (`::highlight`): `highlight-outline-*`, `highlight-color-*`, … */
			"highlight-",
			"outline-offset-",
			"outline-",
			"outline",
			"resize",
			"snap-",
			"focus-",
		],
	},
	{
		id: "filter",
		prefixes: [
			"backdrop-",
			"blur-",
			"brightness-",
			"contrast-",
			"grayscale-",
			"hue-rotate-",
			"invert-",
			"saturate-",
			"sepia-",
			"filter-none",
			"filter",
		],
	},
	{ id: "others", prefixes: [] },
];
