/**
 * Shared constants (Tailwind heuristics, regexes). Keep magic values out of logic files.
 *
 * Tailwind’s full utility set is not enumerable here; namespaces are a **heuristic** subset.
 */

/** Regex: common one-word Tailwind utilities. */
export const COMMON_UTILITIES =
	/^(?:flex|grid|inline|block|inline-block|inline-flex|table|table-cell|hidden|visible|static|fixed|absolute|relative|sticky|contents|border|underline|overline|ring|snap|isolate|contain|box-border|box-content|antialiased|subpixel-antialiased|italic|not-italic|uppercase|lowercase|capitalize|normal-case|truncate|resize|transition|transform|select-none|select-text|select-all|select-auto|sr-only|not-sr-only|clearfix|decoration-slice|decoration-clone|break-normal|break-words|break-all|break-keep|indent-0|outline-none)$/;

/** First segment of hyphenated utilities — extend per project/plugins. */
export const COMMON_PREFIXES: readonly string[] = [
	"p",
	"px",
	"py",
	"pt",
	"pb",
	"pl",
	"pr",
	"m",
	"mx",
	"my",
	"mt",
	"mb",
	"ml",
	"mr",
	"space",
	"gap",
	"w",
	"min",
	"max",
	"h",
	"size",
	"text",
	"font",
	"leading",
	"tracking",
	"line",
	"bg",
	"from",
	"via",
	"to",
	"border",
	"rounded",
	"ring",
	"divide",
	"outline",
	"shadow",
	"opacity",
	"z",
	"inset",
	"top",
	"right",
	"bottom",
	"left",
	"grid",
	"col",
	"row",
	"flex",
	"grow",
	"shrink",
	"basis",
	"order",
	"self",
	"place",
	"items",
	"justify",
	"content",
	"align",
	"whitespace",
	"break",
	"truncate",
	"transition",
	"duration",
	"ease",
	"delay",
	"animate",
	"scale",
	"rotate",
	"translate",
	"skew",
	"origin",
	"fill",
	"stroke",
	"object",
	"overflow",
	"overscroll",
	"scroll",
	"snap",
	"touch",
	"select",
	"pointer",
	"resize",
	"appearance",
	"prose",
	"accent",
	"caret",
	"not",
	"will",
	"aspect",
	"columns",
	"float",
	"clear",
	"isolate",
	"mix",
	"filter",
	"blur",
	"brightness",
	"contrast",
	"grayscale",
	"hue",
	"invert",
	"saturate",
	"sepia",
	"drop",
	"backdrop",
	"list",
	"decoration",
	"underline",
	"indent",
	"align",
	"vertical",
	"container",
	"screen",
	"auto",
	"full",
	"fit",
	"svh",
	"lvh",
	"dvh",
];

export const COMMON_UTILITY_NAMESPACE: ReadonlySet<string> = new Set(
	COMMON_PREFIXES,
);

/** Bracket chunks that usually mean arbitrary values / selectors in Tailwind v3+. */
export const ARBITRARY_BRACKETS = /\[[^\]]+\]/;
